name: evo
description: Evolution!

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.17.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    flame: ^1.2.0
    flame_oxygen: ^0.1.3
    google_fonts: ^3.0.1
    provider: ^6.0.3

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/images/creature.png
        - assets/images/eating-animation.png
